"""Vendor-neutral chat message types for LLM providers."""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any, Literal

MessageRole = Literal["system", "user", "assistant", "tool"]


@dataclass(frozen=True)
class ToolCallRequest:
    """A request from the model to invoke a tool."""

    id: str
    name: str
    arguments: Mapping[str, Any]


@dataclass(frozen=True)
class BaseMessage(ABC):
    """Base class for messages passed to an LLM provider."""

    content: str

    @property
    @abstractmethod
    def role(self) -> MessageRole:
        """Return the provider-neutral role of this message."""

        raise NotImplementedError


@dataclass(frozen=True)
class SystemMessage(BaseMessage):
    """A message that provides instructions or context to the model."""

    @property
    def role(self) -> Literal["system"]:
        return "system"


@dataclass(frozen=True)
class HumanMessage(BaseMessage):
    """A message from the user."""

    @property
    def role(self) -> Literal["user"]:
        return "user"


@dataclass(frozen=True)
class AIMessage(BaseMessage):
    """A message generated by the model, optionally requesting tools."""

    tool_calls: tuple[ToolCallRequest, ...] = ()

    @property
    def role(self) -> Literal["assistant"]:
        return "assistant"


@dataclass(frozen=True)
class ToolMessage(BaseMessage):
    """A tool result associated with a previous model tool call."""

    tool_call_id: str

    @property
    def role(self) -> Literal["tool"]:
        return "tool"


# Keep the existing name available for type annotations during the migration
# to the more specific message classes.
Message = BaseMessage
